### ISSUE TITLE
optimize_transport_and_conversion.py error 

### ISSUE THREAD

**Issue by Bachirou06** [ClimateCompatibleGrowth/GeoH2#20]
Hi all, 
I am novice using GeoH2, i am running an analysis for given country. I came accros an error related to the coordinate normalization in geodesic which seems to be depreciated. I will be grateful with some hint. Below is the error 

geopy                     2.4.1              pyhd8ed1ab_1    conda-forge
geos                      3.11.0               h39d44d4_0    conda-forge

for i in range(len(hexagon)):
        # calculate distance to demand for each hexagon
        poly = shapely.wkt.loads(str(hexagon['geometry'][i]))
        center = poly.centroid
        demand_coords = (demand_center_list.loc[d,'Lat [deg]'], demand_center_list.loc[d,'Lon [deg]'])
        hexagon_coords = (center.y, center.x)
        dist = geopy.distance.geodesic(demand_coords, hexagon_coords).km
        
        distance_to_demand[i] = dist
……………………………
……………
……
….
..
187 latitude, longitude, altitude = \
--> 188     _normalize_coordinates(latitude, longitude, altitude)
    190 self = super().__new__(cls)
    191 self.latitude = latitude

File [~\AppData\Local\miniconda3\envs\geoh2\lib\site-packages\geopy\point.py:74](http://localhost:8892/lab/tree/~/AppData/Local/miniconda3/envs/geoh2/lib/site-packages/geopy/point.py#line=73), in _normalize_coordinates(latitude, longitude, altitude)
     66 if abs(latitude) > 90:
     67     warnings.warn('Latitude normalization has been prohibited in the newer '
     68                   'versions of geopy, because the normalized value happened '
     69                   'to be on a different pole, which is probably not what was '
   (...)
     72                   '(latitude, longitude) or (y, x) in Cartesian terms.',
     73                   UserWarning, stacklevel=3)
---> 74     raise ValueError('Latitude must be in the [-90; 90] range.')
     76 if abs(longitude) > 180:
     77     # Longitude normalization is pretty straightforward and doesn't seem
     78     # to be error-prone, so there's nothing to complain about.
     79     longitude = _normalize_angle(longitude, 180.0)

ValueError: Latitude must be in the [-90; 90] range.

**Comment by samiyhanaqvi** [comment]
Hi,

Thank you for emailing.

The error is saying that the Latitude must be between -90 and 90.

From the error snippet that you have sent, I am not able to see which line in the code the error is coming from, but it could help to check your parameter file where you have your latitude stored.

Many thanks,
Samiyha
________________________________
From: DJIBO BOUBE Bachirou ***@***.***>
Sent: 10 October 2024 23:20
To: ClimateCompatibleGrowth/GeoH2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ClimateCompatibleGrowth/GeoH2] optimize_transport_and_conversion.py error (Issue #20)


Hi all,
I am novice using GeoH2, i am running an analysis for given country. I came accros an error related to the coordinate normalization in geodesic which seems to be depreciated. I will be grateful with some hint. Below is the error

for i in range(len(hexagon)):
# calculate distance to demand for each hexagon
poly = shapely.wkt.loads(str(hexagon['geometry'][i]))
center = poly.centroid
demand_coords = (demand_center_list.loc[d,'Lat [deg]'], demand_center_list.loc[d,'Lon [deg]'])
hexagon_coords = (center.y, center.x)
dist = geopy.distance.geodesic(demand_coords, hexagon_coords).km

    distance_to_demand[i] = dist


……………………………
……………
……
….
..
187 latitude, longitude, altitude =
--> 188 _normalize_coordinates(latitude, longitude, altitude)
190 self = super().new(cls)
191 self.latitude = latitude

File ~\AppData\Local\miniconda3\envs\geoh2\lib\site-packages\geopy\point.py:74<http://localhost:8892/lab/tree/~/AppData/Local/miniconda3/envs/geoh2/lib/site-packages/geopy/point.py#line=73>, in _normalize_coordinates(latitude, longitude, altitude)
66 if abs(latitude) > 90:
67 warnings.warn('Latitude normalization has been prohibited in the newer '
68 'versions of geopy, because the normalized value happened '
69 'to be on a different pole, which is probably not what was '
(...)
72 '(latitude, longitude) or (y, x) in Cartesian terms.',
73 UserWarning, stacklevel=3)
---> 74 raise ValueError('Latitude must be in the [-90; 90] range.')
76 if abs(longitude) > 180:
77 # Longitude normalization is pretty straightforward and doesn't seem
78 # to be error-prone, so there's nothing to complain about.
79 longitude = _normalize_angle(longitude, 180.0)

ValueError: Latitude must be in the [-90; 90] range.

**Comment by Bachirou06** [comment]
Thanks for your prompte response:
The error is on the line 115
115 dist = geopy.distance.geodesic(demand_coords, hexagon_coords).km

i have even shift back to the geopy 2.0 instead of 2.4.1

Kindly receive below further explanation.

[C:\Users\hp\AppData\Local\miniconda3\envs\geoh2\lib\site-packages\geopy\point.py:471](file:///C:/Users/hp/AppData/Local/miniconda3/envs/geoh2/lib/site-packages/geopy/point.py#line=470): UserWarning: Latitude normalization has been prohibited in the newer versions of geopy, because the normalized value happened to be on a different pole, which is probably not what was meant. If you pass coordinates as positional args, please make sure that the order is (latitude, longitude) or (y, x) in Cartesian terms.
  return cls(*args)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[15], line 115
    113 #hexagon_coords = (center.x, center.y)
    114 hexagon_coords = (center.y, center.x)
--> 115 dist = geopy.distance.geodesic(demand_coords, hexagon_coords).km
    117 distance_to_demand[i] = dist
    119 #!!! maybe this is the place to set a restriction based on distance to demand center-- for all hexagons with a distance below some cutoff point
    120 # label demand location under consideration

File [~\AppData\Local\miniconda3\envs\geoh2\lib\site-packages\geopy\distance.py:418](http://localhost:8957/lab/tree/~/AppData/Local/miniconda3/envs/geoh2/lib/site-packages/geopy/distance.py#line=417), in geodesic.__init__(self, *args, **kwargs)
    416 self.set_ellipsoid(kwargs.pop('ellipsoid', 'WGS-84'))
    417 major, minor, f = self.ELLIPSOID
--> 418 super().__init__(*args, **kwargs)

File [~\AppData\Local\miniconda3\envs\geoh2\lib\site-packages\geopy\distance.py:201](http://localhost:8957/lab/tree/~/AppData/Local/miniconda3/envs/geoh2/lib/site-packages/geopy/distance.py#line=200), in Distance.__init__(self, *args, **kwargs)
    199 elif len(args) > 1:
    200     for a, b in util.pairwise(args):
--> 201         kilometers += self.measure(a, b)
    203 kilometers += units.kilometers(**kwargs)
    204 self.__kilometers = kilometers

File [~\AppData\Local\miniconda3\envs\geoh2\lib\site-packages\geopy\distance.py:438](http://localhost:8957/lab/tree/~/AppData/Local/miniconda3/envs/geoh2/lib/site-packages/geopy/distance.py#line=437), in geodesic.measure(self, a, b)
    437 def measure(self, a, b):
--> 438     a, b = Point(a), Point(b)
    439     _ensure_same_altitude(a, b)
    440     lat1, lon1 = a.latitude, a.longitude

File [~\AppData\Local\miniconda3\envs\geoh2\lib\site-packages\geopy\point.py:174](http://localhost:8957/lab/tree/~/AppData/Local/miniconda3/envs/geoh2/lib/site-packages/geopy/point.py#line=173), in Point.__new__(cls, latitude, longitude, altitude)
    170             raise TypeError(
    171                 "Failed to create Point instance from %r." % (arg,)
    172             )
    173         else:
--> 174             return cls.from_sequence(seq)
    176 if single_arg:
    177     raise ValueError(
    178         'A single number has been passed to the Point '
    179         'constructor. This is probably a mistake, because '
   (...)
    183         'to get rid of this error.'
    184     )

File [~\AppData\Local\miniconda3\envs\geoh2\lib\site-packages\geopy\point.py:471](http://localhost:8957/lab/tree/~/AppData/Local/miniconda3/envs/geoh2/lib/site-packages/geopy/point.py#line=470), in Point.from_sequence(cls, seq)
    468 if len(args) > 3:
    469     raise ValueError('When creating a Point from sequence, it '
    470                      'must not have more than 3 items.')
--> 471 return cls(*args)

File [~\AppData\Local\miniconda3\envs\geoh2\lib\site-packages\geopy\point.py:187](http://localhost:8957/lab/tree/~/AppData/Local/miniconda3/envs/geoh2/lib/site-packages/geopy/point.py#line=186), in Point.__new__(cls, latitude, longitude, altitude)
    176 if single_arg:
    177     raise ValueError(
    178         'A single number has been passed to the Point '
    179         'constructor. This is probably a mistake, because '
   (...)
    183         'to get rid of this error.'
    184     )
    186 latitude, longitude, altitude = \
--> 187     _normalize_coordinates(latitude, longitude, altitude)
    189 self = super().__new__(cls)
    190 self.latitude = latitude

File [~\AppData\Local\miniconda3\envs\geoh2\lib\site-packages\geopy\point.py:74](http://localhost:8957/lab/tree/~/AppData/Local/miniconda3/envs/geoh2/lib/site-packages/geopy/point.py#line=73), in _normalize_coordinates(latitude, longitude, altitude)
     66 if abs(latitude) > 90:
     67     warnings.warn('Latitude normalization has been prohibited in the newer '
     68                   'versions of geopy, because the normalized value happened '
     69                   'to be on a different pole, which is probably not what was '
   (...)
     72                   '(latitude, longitude) or (y, x) in Cartesian terms.',
     73                   UserWarning, stacklevel=3)
---> 74     raise ValueError('Latitude must be in the [-90; 90] range.')
     76 if abs(longitude) > 180:
     77     # Longitude normalization is pretty straightforward and doesn't seem
     78     # to be error-prone, so there's nothing to complain about.
     79     longitude = _normalize_angle(longitude, 180.0)

ValueError: Latitude must be in the [-90; 90] range.

**Comment by samiyhanaqvi** [comment]
Thank you for sharing more information.

Can you check your Parameters/demand_parameters.xlsx file and share your latitude and longitude values with me please.

Many thanks,
Samiyha
________________________________

**Comment by Bachirou06** [comment]
> Thank you for sharing more information. Can you check your Parameters/demand_parameters.xlsx file and share your latitude and longitude values with me please. Many thanks, Samiyha
Lat [deg] : 13, Lon[deg]:  2

![image](https://github.com/user-attachments/assets/9ebfce10-fd16-4b25-8387-e890a98af1aa)

**Comment by samiyhanaqvi** [comment]
I've just realised that you might be using an older version of the repo. Have you pulled from the repo recently to update your version?

Please try the below when you are in the GeoH2 folder (if you haven't updated it since September 25th):
>> git pull origin main

And then please read the Readme as we have updated the code.

If this is not the case, please could you send a screenshot(s) of the full error in your terminal/console.

Many thanks,
Samiyha
________________________________

**Comment by Bachirou06** [comment]
Hi @samiyhanaqvi,

I'm sorry for not getting back to you sooner, but I'm using the two versions. The current issue is related to the first version
I am still exploring the new versions I will come back for further information regarding.

Thanks for reaching out.

**Comment by Bachirou06** [comment]
Hi @samiyhanaqvi 

This what i got as error, i have even the system to linux:

(geoh2s) bachirou@djibo:~/GeoH2-main_new_NE$ snakemake -j 1 Resources/hex_transport_NE.geojson
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                                  count
---------------------------------  -------
optimize_transport_and_conversion        1
total                                    1

Select jobs to execute...

[Thu Oct 24 09:01:53 2024]
rule optimize_transport_and_conversion:
    input: Data/hexagons_with_country_NE.geojson, Parameters/technology_parameters.xlsx, Parameters/demand_parameters.xlsx, Parameters/country_parameters.xlsx, Parameters/conversion_parameters.xlsx, Parameters/transport_parameters.xlsx, Parameters/pipeline_parameters.xlsx
    output: Resources/hex_transport_NE.geojson
    jobid: 0
    reason: Missing output files: Resources/hex_transport_NE.geojson
    wildcards: country=NE
    resources: tmpdir=/tmp

Traceback (most recent call last):
  File "/home/bachirou/GeoH2-main_new_NE/.snakemake/scripts/tmp2uj6l_u0.optimize_transport_and_conversion.py", line 57, in <module>
    country_parameters = pd.read_excel(country_parameters,
  File "/home/bachirou/miniconda3/envs/geoh2s/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 517, in read_excel
    data = io.parse(
  File "/home/bachirou/miniconda3/envs/geoh2s/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1629, in parse
    return self._reader.parse(
  File "/home/bachirou/miniconda3/envs/geoh2s/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 931, in parse
    raise err
  File "/home/bachirou/miniconda3/envs/geoh2s/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 918, in parse
    output[asheetname] = parser.read(nrows=nrows)
  File "/home/bachirou/miniconda3/envs/geoh2s/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/bachirou/miniconda3/envs/geoh2s/lib/python3.10/site-packages/pandas/io/parsers/python_parser.py", line 292, in read
    index, result_columns = self._make_index(
  File "/home/bachirou/miniconda3/envs/geoh2s/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py", line 370, in _make_index
    simple_index = self._get_simple_index(alldata, columns)
  File "/home/bachirou/miniconda3/envs/geoh2s/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py", line 402, in _get_simple_index
    i = ix(idx)
  File "/home/bachirou/miniconda3/envs/geoh2s/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py", line 397, in ix
    raise ValueError(f"Index {col} invalid")
ValueError: Index Country invalid (sheet: 0)
[Thu Oct 24 09:01:54 2024]
Error in rule optimize_transport_and_conversion:
    jobid: 0
    input: Data/hexagons_with_country_NE.geojson, Parameters/technology_parameters.xlsx, Parameters/demand_parameters.xlsx, Parameters/country_parameters.xlsx, Parameters/conversion_parameters.xlsx, Parameters/transport_parameters.xlsx, Parameters/pipeline_parameters.xlsx
    output: Resources/hex_transport_NE.geojson

RuleException:
CalledProcessError in file /home/bachirou/GeoH2-main_new_NE/Snakefile, line 55:
Command 'set -euo pipefail;  /home/bachirou/miniconda3/envs/geoh2s/bin/python3.10 /home/bachirou/GeoH2-main_new_NE/.snakemake/scripts/tmp2uj6l_u0.optimize_transport_and_conversion.py' returned non-zero exit status 1.
  File "/home/bachirou/GeoH2-main_new_NE/Snakefile", line 55, in __rule_optimize_transport_and_conversion
  File "/home/bachirou/miniconda3/envs/geoh2s/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-24T090153.559794.snakemake.log

**Comment by samiyhanaqvi** [comment]
Thank you for sharing this.

The error seems to be with the country parameters excel file. I would recommend checking that the format of the file is like the example file we have in the repo. If that's fine, you can try opening the file and "save as" an excel workbook as it could be in a different format, but with the same file extension.

How are you finding using the up-to-date software?

**Comment by Bachirou06** [comment]
Hi
Thanks a lot for the support @samiyhanaqvi. I have been able to find out the issue and correct.
I am impressed by the flexibility of the updated version of the Geoh2 and the use of snakemake for running the code easily. Many thanks to the CCG team, you did amazing work. Keep it going

**Comment by samiyhanaqvi** [comment]
No worries. I am going to close this issue now.
