### ISSUE TITLE
`theo_wind` and `theo_pv` unit errors

### ISSUE THREAD

**Issue by paulapreuss** [ClimateCompatibleGrowth/GeoH2#21]
Hi CCG team,

I have been browsing your tool to apply it to a different case study - first of all, I am very impressed by it and think it is an extremely nice and comprehensive tool. Great job!

I am a bit confused about the `theo_wind` and `theo_pv` parameters that result form the `GLAES` land exclusion though. By looking at the code from GeoH2-data-prep (`combine_glaes_spider.py`) it seems that the `theo_pv` and `theo_wind` parameters applied to each hexagon refer to the max. _number_ of turbines/PV modules that would be possible to place within a hexagon:

```
    # Group by polygon and count the points within each polygon
    pv_point_counts = spatial_join.groupby('index_right').size()

    # Merge the point counts with the 'hex' GeoDataFrame based on the index
    hex['theo_pv'] = pv_point_counts

```

However, later in GeoH2, when it comes to optimizing each hexagon, the number from `theo_pv` and `theo_wind` are assigned to `p_nom_max` in `optimize_hydrogen_plant.py`.

```
    # specify maximum capacity based on land use
    n.generators.loc['Wind','p_nom_max'] = wind_max_capacity # --> this is passed as hexagons.loc[hexagon,'theo_turbines']
    n.generators.loc['Solar','p_nom_max'] = pv_max_capacity # --> this is passed as hexagons.loc[hexagon,'theo_pv']

```
Since the value set on `p_nom_max` refers to maximum _capacity_ and not to maximum _number_ of turbines/PV modules, should this number not be multiplied by the maximum capacity of the assumed turbines/modules? Or am I understanding something wrong/did I miss something?

**Comment by alycialeonard** [comment]
Hi Paula, thanks for flagging this! You are exactly correct, `theo_pv` and `theo_wind` should represent the maximum capacity off all theoretically installable turbines/PV modules in MW. This is assumed to be handled during preparation of spatial input data. However, we should add this assumption to our readme so it is clear to users. We will get that done!
